---
- name: Prepare
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - python3-pip
          - python3-kubernetes
          - python3-urllib3
          - curl
          - jq
        state: present
        update_cache: yes

    - name: Create test directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /oem
        - /etc/default
        - /tmp/harvester-configs
        - /tmp/harvester-terraform-test

    - name: Create mock GRUB file
      copy:
        content: |
          # Mock GRUB configuration
          GRUB_DEFAULT=0
          GRUB_TIMEOUT=5
          GRUB_CMDLINE_LINUX=""
        dest: /etc/default/grub
        mode: '0644'

    - name: Create mock update-grub script
      copy:
        content: |
          #!/bin/bash
          echo "Mock update-grub executed"
          exit 0
        dest: /usr/sbin/update-grub
        mode: '0755'

    - name: Ensure Python kubernetes module is available
      debug:
        msg: "Using system python3-kubernetes package"

    - name: Create test SSH key
      copy:
        content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC test@example.com"
        dest: /tmp/test-ssh-key.pub
        mode: '0644'

    - name: Set test environment variables
      copy:
        content: |
          export INFISICAL_CLIENT_ID="test-client-id"
          export INFISICAL_CLIENT_SECRET="test-client-secret"
          export INFISICAL_PROJECT_ID="test-project-id"
        dest: /tmp/test-env.sh
        mode: '0644'