---
- name: Verify
  hosts: all
  gather_facts: yes
  tasks:
    - name: Verify network configuration files were created
      block:
        - name: Check network config directory exists
          stat:
            path: /tmp/harvester-network-configs
          register: network_dir
          failed_when: network_dir.stat.exists

        - name: Verify OEM directory was created
          stat:
            path: /oem
          register: oem_dir
          failed_when: not oem_dir.stat.exists or not oem_dir.stat.isdir

    - name: Verify GRUB configuration updates
      block:
        - name: Check GRUB configuration exists
          stat:
            path: /etc/default/grub
          register: grub_file
          failed_when: not grub_file.stat.exists

        - name: Verify GRUB backup was created
          shell: ls -1 /etc/default/grub.backup.* 2>/dev/null | wc -l
          register: grub_backups
          failed_when: false

    - name: Verify sysctl configuration
      block:
        - name: Check sysctl configuration file
          stat:
            path: /etc/sysctl.d/99-harvester.conf
          register: sysctl_file
          failed_when: not sysctl_file.stat.exists

        - name: Verify sysctl content
          lineinfile:
            path: /etc/sysctl.d/99-harvester.conf
            line: "net.ipv4.ip_forward = 1"
            state: present
          check_mode: yes
          register: sysctl_forward
          failed_when: sysctl_forward.changed

    - name: Verify Harvester configuration templates
      block:
        - name: Check Harvester init config was generated
          stat:
            path: /tmp/harvester-configs/harvester-init.yaml
          register: init_config
          failed_when: init_config.stat.exists  # Should be cleaned up

        - name: Check join configs were generated
          stat:
            path: /tmp/harvester-join-configs
          register: join_configs
          failed_when: join_configs.stat.exists  # Should be cleaned up

    - name: Verify Terraform setup
      block:
        - name: Check Terraform directory exists
          stat:
            path: /tmp/harvester-terraform-test
          register: terraform_dir
          failed_when: not terraform_dir.stat.exists or not terraform_dir.stat.isdir

        - name: Check Terraform configuration files
          stat:
            path: "/tmp/harvester-terraform-test/{{ item }}"
          loop:
            - versions.tf
            - main.tf
            - vm-example.tf
            - .gitignore
          register: terraform_files
          failed_when: not item.stat.exists

        - name: Verify Terraform provider configuration
          lineinfile:
            path: /tmp/harvester-terraform-test/versions.tf
            line: '    source = "harvester/harvester"'
            state: present
          check_mode: yes
          register: terraform_provider
          failed_when: terraform_provider.changed

    - name: Verify kernel modules configuration
      block:
        - name: Check VFIO modules config exists
          stat:
            path: /etc/modules-load.d/vfio.conf
          register: vfio_modules
          # Should only exist for nodes with PCIe devices
          failed_when: false

    - name: Verify test mode execution
      debug:
        msg: |
          Verification Complete:
          - Network configurations: Created and cleaned
          - GRUB configurations: Updated for IOMMU
          - Sysctl parameters: Applied
          - Terraform setup: Configured
          - Test mode: Successfully prevented actual deployment
          
          All verifications passed!