- name: defaultConfig
  hosts: opnsense
  connection: local
  gather_facts: no
  vars:
    infisicalClientSecret: "{{ lookup('ansible.builtin.env', 'INFISICAL_CLIENT_SECRET', default=undef()) }}"
    opnsenseApiKey: "{{ lookup(
      'infisical.vault.read_secrets',
      universal_auth_client_id='72fdfa59-56b2-4d2e-9dde-cd5a4d5ef3ea',
      universal_auth_client_secret=infisicalClientSecret,
      project_id='e0ff40f2-e63c-4ffc-9233-a66c46a47b2e',
      path='/',
      env_slug='prod',
      url='https://app.infisical.com',
      secret_name='opnsenseApiKey',
      )
    }}"
    opnsenseApiSecret: "{{ lookup(
      'infisical.vault.read_secrets',
      universal_auth_client_id='72fdfa59-56b2-4d2e-9dde-cd5a4d5ef3ea',
      universal_auth_client_secret=infisicalClientSecret,
      project_id='e0ff40f2-e63c-4ffc-9233-a66c46a47b2e',
      path='/',
      env_slug='prod',
      url='https://app.infisical.com',
      secret_name='opnsenseApiSecret',
      )
    }}"
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: '10.0.0.1'
      ssl_verify: false
      api_port: '443'
      api_key: "{{ opnsenseApiKey.value }}"
      api_secret: "{{ opnsenseApiSecret.value }}"

  tasks:
    - name: install libvirt

    - name: read vlan
      ansibleguy.opnsense.list:
        target: 'interface_vlan'
      register: vlan

    - name: printing
      ansible.builtin.debug:
        var: vlan.data

    - name: add main vlan
      ansibleguy.opnsense.interface_vlan:
        interface: 're0'
        tag: 10
        description: 'main vlan'

    - name: read vlan
      ansibleguy.opnsense.list:
        target: 'interface_vlan'
      register: vlan

    - name: printing
      ansible.builtin.debug:
        var: vlan.data




