---
galaxy_info:
  author: homelab
  description: Build and cache Harvester base images for fast testing and deployment
  company: Homelab
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - harvester
    - hci
    - kubernetes
    - virtualization
    - qemu
    - image-builder

dependencies: []