---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted 