---
- name: Converge
  hosts: all
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-lxml
          - libvirt-daemon-system
          - qemu-kvm
          - libvirt-clients
          - bridge-utils
          - virtinst
          - systemd
        state: present

    - name: Start and enable libvirt
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Include VyOS setup role
      ansible.builtin.include_role:
        name: ../../../roles/vyos_setup
      vars:
        vyos_network_mode: nat
        vyos_configure_router: false
        vyos_vm_ip: "192.168.122.50"
        vyos_vm_gateway: "192.168.122.1"
        vyos_vm_nameservers:
          - "8.8.8.8"
          - "8.8.4.4"
        vyos_vm_os_variant: "generic"
        vyos_vm:
          name: vyos-router
          memory: 1024
          vcpus: 2
          disk_path: /var/lib/libvirt/images/vyos-router.qcow2
          disk_size: 10G 