---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: vyos-test
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - nexus
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      retry_files_enabled: false
      host_key_checking: false
      remote_tmp: /tmp/.ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: community.docker.docker
verifier:
  name: ansible 