---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: vyos-test
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /dev/kvm:/dev/kvm
    cgroupns_mode: host
    privileged: true
    capabilities:
      - SYS_ADMIN
    groups:
      - nexus
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      retry_files_enabled: false
      host_key_checking: false
      remote_tmp: /tmp/ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker
verifier:
  name: ansible 