---
# Infisical Configuration
vyos_infisical_client_id: "{{ lookup('env', 'INFISICAL_CLIENT_ID') }}"

vyos_infisical_client_secret: "{{ lookup('env', 'INFISICAL_CLIENT_SECRET') }}"

vyos_infisical_project_id: "{{ lookup('env', 'INFISICAL_PROJECT_ID') }}"

vyos_infisical_url: "https://app.infisical.com"

# VyOS VM Configuration
vyos_vm:
  name: vyos-router
  memory: 4096
  vcpus: 2
  disk_size: 20G
  disk_path: /var/lib/libvirt/images/vyos-router.qcow2

# VyOS Build Configuration
# Whether to build a new VyOS image from ISO
vyos_build_image: false

# Path to the VyOS ISO file
# Use VYOS_ISO_PATH environment variable to override
vyos_iso_path: "{{ playbook_dir }}/../images/vyos/vyos-current.iso"

# Path where cloud-init ISO will be created
vyos_cloud_init_iso: /var/lib/libvirt/images/vyos-cloud-init.iso

# VyOS Network Configuration
# IP address assigned to the VyOS VM
vyos_vm_ip: "192.168.122.50"

# SSH port for accessing VyOS (mapped from VM port 22)
vyos_ssh_port: 2222

# HTTPS port for VyOS web interface
vyos_web_port: 443

# Security Configuration
vyos_admin_user: admin
# These should be overridden by prepare.yaml in test mode or set from Infisical in production
# Providing defaults to avoid undefined variable errors
vyos_admin_password: "TestPassword123!"
vyos_ansible_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC test@molecule"
vyos_ansible_ssh_private_key: "TEST_PRIVATE_KEY"
vyos_security_hardening: true

# Cloud-Init Configuration
vyos_cloud_init_enabled: true

# Fail2ban Configuration
vyos_enable_fail2ban: true

# Network Mode Configuration
# Options: bridge (production), nat (testing), macvtap
vyos_network_mode: bridge

# Enable VLAN configuration on the router
vyos_enable_vlans: true

# Configure router settings (firewall, NAT, etc.)
vyos_configure_router: true

# Configure VLANs on the host system
vyos_configure_host_vlans: false

# Use Open vSwitch for networking (recommended for production)
vyos_use_ovs: true

# Interface that will carry VLAN traffic
vyos_trunk_interface: "eth1"

# WAN Interface Configuration
# Interface connected to the internet/upstream network
vyos_wan_interface: "eth0"
vyos_wan_dhcp: true

# Domain Configuration
vyos_domain: "awynn.info"
vyos_vlan_domains:
  dmz: "public.{{ vyos_domain }}"
  secure: "private.{{ vyos_domain }}"
  management: "management.{{ vyos_domain }}"
  logging: "logs.{{ vyos_domain }}"

# Updated VLAN Network Definitions with /16 subnets
vyos_vlan_networks:
  - name: "dmz"
    vlan_id: 10
    description: "DMZ Network - External facing services"
    subnet: "10.10.0.0/16"  # Changed from /24
    gateway: "10.10.0.1"
    domain: "{{ vyos_vlan_domains.dmz }}"
    bridge_name: "br-dmz"
    dhcp_enabled: true
    dhcp_range: "10.10.0.100-10.10.0.199"
    dns_servers:
      - "10.10.0.1"
      - "1.1.1.1"
    firewall_rules:
      - rule: 10
        action: "accept"
        source: "10.10.0.0/16"
        destination: "0.0.0.0/0"
        description: "Allow DMZ to Internet"
      - rule: 20
        action: "drop"
        source: "10.10.0.0/16"
        destination: "10.0.0.0/8"
        description: "Block DMZ to all internal networks"

  - name: "untrusted-wifi"
    vlan_id: 20
    description: "Untrusted WiFi - Guest devices"
    subnet: "10.20.0.0/16"  # Changed from /24
    gateway: "10.20.0.1"
    bridge_name: "br-untrusted"
    dhcp_enabled: true
    dhcp_range: "10.20.0.100-10.20.0.199"
    dns_servers:
      - "10.20.0.1"
      - "1.1.1.1"
    firewall_rules:
      - rule: 10
        action: "accept"
        source: "10.20.0.0/16"
        destination: "0.0.0.0/0"
        description: "Allow guest WiFi to Internet only"
      - rule: 20
        action: "drop"
        source: "10.20.0.0/16"
        destination: "10.0.0.0/8"
        description: "Block guest WiFi to all internal networks"

  - name: "trusted-wifi"
    vlan_id: 30
    description: "Trusted WiFi - Personal devices"
    subnet: "10.30.0.0/16"  # Changed from /24
    gateway: "10.30.0.1"
    bridge_name: "br-trusted"
    dhcp_enabled: true
    dhcp_range: "10.30.0.100-10.30.0.199"
    dns_servers:
      - "10.30.0.1"
      - "1.1.1.1"
    firewall_rules:
      - rule: 10
        action: "accept"
        source: "10.30.0.0/16"
        destination: "0.0.0.0/0"
        description: "Allow trusted WiFi to Internet"
      - rule: 20
        action: "accept"
        source: "10.30.0.0/16"
        destination: "10.50.0.0/16"
        description: "Allow trusted WiFi to secure network"
      - rule: 30
        action: "drop"
        source: "10.30.0.0/16"
        destination: "10.0.0.0/8"
        description: "Block trusted WiFi to other internal networks"

  - name: "iot"
    vlan_id: 40
    description: "IoT Network - Isolated IoT devices"
    subnet: "10.40.0.0/16"  # Changed from /24
    gateway: "10.40.0.1"
    bridge_name: "br-iot"
    dhcp_enabled: true
    dhcp_range: "10.40.0.100-10.40.0.199"
    dns_servers:
      - "10.40.0.1"
      - "1.1.1.1"
    firewall_rules:
      - rule: 10
        action: "accept"
        source: "10.40.0.0/16"
        destination: "0.0.0.0/0"
        description: "Allow IoT to Internet"
      - rule: 20
        action: "drop"
        source: "10.40.0.0/16"
        destination: "10.0.0.0/8"
        description: "Block IoT to all internal networks"

  - name: "secure"
    vlan_id: 50
    description: "Secure Network - Main trusted network"
    subnet: "10.50.0.0/16"  # Changed from /24
    gateway: "10.50.0.1"
    domain: "{{ vyos_vlan_domains.secure }}"
    bridge_name: "br-secure"
    dhcp_enabled: true
    dhcp_range: "10.50.0.100-10.50.0.199"
    dns_servers:
      - "10.50.0.1"
      - "1.1.1.1"
    firewall_rules:
      - rule: 10
        action: "accept"
        source: "10.50.0.0/16"
        destination: "0.0.0.0/0"
        description: "Allow Secure to Internet"
      - rule: 20
        action: "accept"
        source: "10.50.0.0/16"
        destination: "10.60.0.0/16"
        description: "Allow Secure to Management via jumphost"
        condition: "via-jumphost"

  - name: "management"
    vlan_id: 60
    description: "Management Network - Server administration"
    subnet: "10.60.0.0/16"  # Changed from /24
    gateway: "10.60.0.1"
    domain: "{{ vyos_vlan_domains.management }}"
    bridge_name: "br-mgmt"
    dhcp_enabled: true
    dhcp_range: "10.60.0.100-10.60.0.199"
    dns_servers:
      - "10.60.0.1"
      - "1.1.1.1"

  - name: "logging"
    vlan_id: 70
    description: "Logging Network - System monitoring"
    subnet: "10.70.0.0/16"  # Changed from /24
    gateway: "10.70.0.1"
    domain: "{{ vyos_vlan_domains.logging }}"
    bridge_name: "br-logging"
    dhcp_enabled: false
    dns_servers:
      - "10.70.0.1"

  - name: "storage"
    vlan_id: 65
    description: "Storage Network - Harvester Longhorn replication"
    subnet: "10.60.65.0/24"
    gateway: "10.60.65.1"
    domain: "storage.{{ vyos_domain }}"
    bridge_name: "br-storage"
    dhcp_enabled: false
    dns_servers:
      - "10.60.65.1"
    firewall_rules:
      - rule: 5
        action: "accept"
        state: 
          established: true
          related: true
        description: "Allow established and related connections"
      - rule: 10
        action: "accept"
        source: "10.60.65.0/24"
        destination: "10.60.65.0/24"
        state:
          new: true
        description: "Allow new storage replication between nodes"
      - rule: 20
        action: "accept"
        source: "10.60.0.0/16"
        destination: "10.60.65.0/24"
        state:
          new: true
        description: "Allow management to initiate connections to storage"
      - rule: 30
        action: "drop"
        source: "10.60.65.0/24"
        destination: "0.0.0.0/0"
        description: "Block storage from initiating Internet connections"
      - rule: 40
        action: "drop"
        source: "10.60.65.0/24"
        destination: "10.0.0.0/8"
        description: "Block storage from initiating connections to other VLANs"

# DNS Configuration
vyos_dns_servers:
  - "1.1.1.1"
  - "1.0.0.1"

# NTP Configuration
vyos_ntp_servers:
  - "pool.ntp.org"

# Jump Host Configuration
vyos_jumphost_ip: "10.60.0.10"
