---
# Ubuntu version: Edit ../.env.yaml to change UBUNTU_VERSION and MOLECULE_DOCKER_IMAGE
# Shared configuration inherited from /.config/molecule/config.yaml

platforms:
  - name: services-test
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    pre_build_image: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    volumes:
      - "${MOLECULE_VOLUME_CGROUP:-/sys/fs/cgroup:/sys/fs/cgroup:rw}"
      - "${MOLECULE_VOLUME_KVM:-/dev/kvm:/dev/kvm}"
    cgroupns_mode: "${MOLECULE_CGROUPNS_MODE:-host}"
    privileged: ${MOLECULE_PRIVILEGED:-true}
    capabilities:
      - "${MOLECULE_CAPABILITY_SYS_ADMIN:-SYS_ADMIN}"
    groups:
      - "${MOLECULE_GROUP:-nexus}" 
