---
collections:
  - name: community.general
    version: ">=1.0.0"
  - name: community.libvirt 
    version: ">=1.0.0"
  - name: community.docker
    version: ">=3.10.4"
  - name: homelab.nexus
    source: ../collections