---
- name: Wait for VyOS to be accessible
  ansible.builtin.wait_for:
    port: "{{ vyos_ssh_port | default(2222) }}"
    host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    delay: 60
    timeout: 300
  when: vyos_vm_ip is defined

- name: Configure VyOS physical interfaces
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 description "WAN Interface"
      - set interfaces ethernet eth0 hw-id auto
      - set interfaces ethernet eth1 description "LAN Trunk Interface"
      - set interfaces ethernet eth1 hw-id auto
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined

- name: Configure WAN interface with DHCP
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 address dhcp
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined and vyos_wan_dhcp | default(true)

- name: Configure VLAN interfaces
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth1 vif {{ item.vlan_id }} description "{{ item.description }}"
      - set interfaces ethernet eth1 vif {{ item.vlan_id }} address {{ item.gateway }}/{{ item.subnet.split('/')[1] }}
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  loop: "{{ vyos_vlan_networks }}"
  when: vyos_vm_ip is defined and vyos_enable_vlans | default(true)

- name: Configure DHCP server for VLANs
  vyos.vyos.vyos_config:
    lines:
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} default-router {{ item.gateway }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} name-server {{ vyos_dns_servers | join(' ') }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} domain-name {{ item.name }}.{{ vyos_private_domain }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} range vlan{{ item.vlan_id }} start {{ item.dhcp_range.split('-')[0] }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} range vlan{{ item.vlan_id }} stop {{ item.dhcp_range.split('-')[1] }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} lease 86400
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  loop: "{{ vyos_vlan_networks }}"
  when: vyos_vm_ip is defined and item.dhcp_enabled | default(false)

- name: Configure NAT masquerading
  vyos.vyos.vyos_config:
    lines:
      - set nat source rule 100 outbound-interface eth0
      - set nat source rule 100 source address 10.0.0.0/8
      - set nat source rule 100 translation address masquerade
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined

- name: Configure DNS forwarding
  vyos.vyos.vyos_config:
    lines:
      - set service dns forwarding listen-address 127.0.0.1
      - set service dns forwarding cache-size 1000
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined

- name: Configure DNS forwarding listen addresses for VLANs
  vyos.vyos.vyos_config:
    lines:
      - set service dns forwarding listen-address {{ item.gateway }}
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  loop: "{{ vyos_vlan_networks }}"
  when: vyos_vm_ip is defined and vyos_enable_vlans | default(true)

- name: Configure DNS forwarding name servers
  vyos.vyos.vyos_config:
    lines:
      - set service dns forwarding name-server {{ item }}
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  loop: "{{ vyos_dns_servers }}"
  when: vyos_vm_ip is defined

- name: Configure NTP servers
  vyos.vyos.vyos_config:
    lines:
      - set system ntp server {{ item }}
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  loop: "{{ vyos_ntp_servers }}"
  when: vyos_vm_ip is defined

- name: Configure SSH service
  vyos.vyos.vyos_config:
    lines:
      - set service ssh port {{ vyos_ssh_port | default(2222) }}
      - set service ssh listen-address 0.0.0.0
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined

- name: Configure HTTPS web interface on management interface
  vyos.vyos.vyos_config:
    lines:
      - set service https listen-address {{ vyos_vm_ip }}
      - set service https port {{ vyos_web_port | default(443) }}
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined

- name: Configure HTTPS web interface on VLAN gateway addresses
  vyos.vyos.vyos_config:
    lines:
      - set service https listen-address {{ item.gateway }}
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  loop: "{{ vyos_vlan_networks }}"
  when: vyos_vm_ip is defined and vyos_enable_vlans | default(true) and item.name in ['secure', 'management']


- name: Configure VyOS save configuration
  vyos.vyos.vyos_config:
    save: true
  vars:
    ansible_network_os: vyos
    ansible_host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    ansible_port: "{{ vyos_ssh_port | default(2222) }}"
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
  when: vyos_vm_ip is defined