---
- name: Converge
  hosts: all
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - auditd
          - ufw
          - systemd
        state: present

    - name: Include security hardening role
      ansible.builtin.include_role:
        name: homelab.nexus.security_hardening 