---
- name: Converge
  hosts: all
  tasks:
    - name: Create test VyOS ISO placeholder
      command: truncate -s 500M {{ vyos_iso_path }}
      args:
        creates: "{{ vyos_iso_path }}"

    - name: Install required packages
      apt:
        name:
          - cloud-image-utils
          - python3-passlib
          - python3-lxml
          - bridge-utils
          - vlan
        state: present
        update_cache: yes

    - name: Generate test SSH key
      openssh_keypair:
        path: /tmp/test_ssh_key
        type: rsa
        size: 2048
      register: ssh_key

    - name: Include vyos_setup role with full configuration
      include_role:
        name: homelab.nexus.vyos_setup
      vars:
        vyos_admin_ssh_key: "{{ ssh_key.public_key }}"
        vyos_test_mode: true
