---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml

driver:
  name: docker

platforms:
  - name: vyos-integration-test
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    pre_build_image: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /dev/kvm:/dev/kvm
    cgroupns_mode: host
    privileged: true
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    groups:
      - nexus

provisioner:
  name: ansible

verifier:
  name: ansible
