---
# DNS Configuration
# Enable Control-D DNS filtering service
network_controld_enabled: true

# Upstream DNS servers for Control-D
# Used when Control-D cannot resolve or for bypassed domains
network_controld_upstream_dns:
  - "1.1.1.1"
  - "1.0.0.1"

# Log level for Control-D service
# Options: debug, info, warn, error
network_controld_log_level: "info"

# DHCP Configuration
# Enable DHCP server (disabled by default as VyOS handles DHCP per VLAN)
network_dhcp_enabled: false

# Interface for DHCP server to listen on
network_dhcp_interface: "eth1"

# DHCP lease time in seconds (86400 = 24 hours)
network_dhcp_lease_time: 86400

# NTP Configuration
# Enable NTP time synchronization service
network_ntp_enabled: true

# NTP servers to sync time with
network_ntp_servers:
  - "pool.ntp.org"
  - "time.cloudflare.com"

# Networks allowed to sync time from this NTP server
network_ntp_allow_clients:
  - "10.0.0.0/8"
  - "192.168.0.0/16"
