---
- name: Install security packages
  apt:
    name:
      - ufw
      - auditd
      - logrotate
    state: present
    update_cache: yes

- name: Configure UFW
  ufw:
    rule: allow
    port: ssh
    proto: tcp
  when: ansible_os_family == "Debian"

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Configure audit rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0640'
  notify: restart auditd

- name: Configure automatic security updates
  apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: Enable automatic security updates
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Ensure SSH directory exists
  file:
    path: /etc/ssh
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd

- name: Include audit setup
  ansible.builtin.import_tasks: audit.yaml

- name: Include SSH hardening
  ansible.builtin.import_tasks: ssh.yaml

- name: Include system hardening
  ansible.builtin.import_tasks: system.yaml 
