---
- name: Configure SSH key-only authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart sshd

- name: Disable root SSH login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart sshd

- name: Configure SSH port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh_port | default(22) }}"
    state: present
  notify: restart sshd

- name: Disable SSH protocol 1
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Protocol"
    line: "Protocol 2"
    state: present
  notify: restart sshd

- name: Configure SSH max auth tries
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?MaxAuthTries"
    line: "MaxAuthTries 3"
    state: present
  notify: restart sshd

- name: Configure SSH client alive interval
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveInterval"
    line: "ClientAliveInterval 300"
    state: present
  notify: restart sshd

- name: Configure SSH client alive count max
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveCountMax"
    line: "ClientAliveCountMax 2"
    state: present
  notify: restart sshd
