---
- name: Converge
  hosts: all
  tasks:
    - name: Verify VyOS ISO exists
      stat:
        path: "{{ vyos_iso_path }}"
      register: vyos_iso_check
      
    - name: Fail if VyOS ISO not found
      fail:
        msg: "VyOS ISO not found at {{ vyos_iso_path }}. Please ensure the image is available."
      when: not vyos_iso_check.stat.exists

    - name: Generate test SSH key
      openssh_keypair:
        path: /tmp/test_ssh_key
        type: rsa
        size: 2048
      register: ssh_key

    - name: Include vyos_setup role with security hardening
      include_role:
        name: homelab.nexus.vyos_setup
      vars:
        vyos_admin_ssh_key: "{{ ssh_key.public_key }}"
