---
galaxy_info:
  role_name: harvester_setup
  namespace: homelab.epyc
  author: homelab
  description: Deploy and configure a 3-node Harvester HCI cluster with PCIe passthrough support
  company: homelab
  license: GPL-3.0
  min_ansible_version: "2.14"
  
  platforms:
    - name: Harvester
      versions:
        - "1.3"
        - "1.4"
    
  galaxy_tags:
    - harvester
    - hci
    - kubernetes
    - virtualization
    - infrastructure
    - pcie
    - passthrough

dependencies: []