---
# Mock VLAN operations for testing
# This file simulates VLAN creation without actually using libvirt

- name: Create mock VLAN state directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /tmp/vyos-test-mock/vlans
    - /tmp/vyos-test-mock/bridges

- name: Create mock VLAN definitions
  copy:
    content: |
      VLAN Name: {{ item.name }}
      VLAN ID: {{ item.vlan_id }}
      Subnet: {{ item.subnet }}
      Bridge: {{ item.bridge_name }}
      State: active
    dest: "/tmp/vyos-test-mock/vlans/{{ item.name }}.conf"
    mode: '0644'
  loop: "{{ vyos_vlan_networks }}"

- name: Create mock bridge interfaces
  file:
    path: "/tmp/vyos-test-mock/bridges/{{ item.bridge_name }}"
    state: touch
    mode: '0644'
  loop: "{{ vyos_vlan_networks }}"

- name: Set mock VLAN facts
  set_fact:
    vyos_vlans_created: true
    vyos_vlans_mock: true

- name: Display mock VLAN info
  debug:
    msg: |
      Mock VLANs created:
      {% for vlan in vyos_vlan_networks %}
      - {{ vlan.name }} (VLAN {{ vlan.vlan_id }}): {{ vlan.subnet }}
      {% endfor %}
      Mock Mode: {{ vyos_vlans_mock }}