---
- name: Verify
  hosts: all
  tasks:
    - name: Check if Docker is running
      command: docker ps
      register: docker_check
      changed_when: false
      failed_when: false

    - name: Verify Docker is operational (skip in test mode if not available)
      assert:
        that:
          - docker_check.rc == 0
        fail_msg: "Docker is not running properly"
      when: docker_check.rc != 2  # Skip if docker command not found

    - name: Check ISO exists
      stat:
        path: "/tmp/vyos-images/vyos-current.iso"
      register: iso_file

    - name: Verify ISO is created
      assert:
        that:
          - iso_file.stat.exists
        fail_msg: "VyOS ISO not created at expected location"

    - name: Verify ISO is valid size
      assert:
        that:
          - iso_file.stat.size > 500000000  # 500MB minimum for real ISO
        fail_msg: "VyOS ISO too small ({{ iso_file.stat.size }} bytes), expected > 500MB"

    - name: Install file command for ISO verification
      apt:
        name: file
        state: present

    - name: Verify ISO is bootable format
      command: file /tmp/vyos-images/vyos-current.iso
      register: iso_type
      changed_when: false

    - name: Assert ISO is bootable
      assert:
        that:
          - "'ISO 9660' in iso_type.stdout"
          - "'bootable' in iso_type.stdout"
        fail_msg: "ISO is not in expected bootable format: {{ iso_type.stdout }}"

    - name: Check symlink to latest ISO
      stat:
        path: "/tmp/vyos-images/vyos-latest.iso"
      register: latest_link

    - name: Verify latest symlink exists
      assert:
        that:
          - latest_link.stat.exists
          - latest_link.stat.islnk
        fail_msg: "Latest ISO symlink not created"

    - name: Test idempotency - run role again
      include_role:
        name: ../../../roles/vyos_image_builder
      vars:
        vyos_build_dir: /tmp/vyos-build
        vyos_images_dir: /tmp/vyos-images
        vyos_version: current
        vyos_architecture: amd64
        vyos_build_by: 'molecule-test'
        vyos_build_type: release
        vyos_docker_image: "vyos/vyos-build:current"
        vyos_build_cleanup: true
        vyos_test_mode: false

    - name: Find all ISO files after second run
      find:
        paths: /tmp/vyos-images
        patterns: "vyos-*.iso"
        file_type: file
      register: iso_count

    - name: Verify no duplicate build (idempotency)
      assert:
        that:
          - iso_count.files | length == 1
        fail_msg: "Multiple ISOs found, idempotency check failed: {{ iso_count.files | map(attribute='path') | list }}"

    - name: Check build directory cleanup
      stat:
        path: /tmp/vyos-build
      register: build_dir

    - name: Verify build cleanup
      assert:
        that:
          - not build_dir.stat.exists
        fail_msg: "Build directory not cleaned up"
        
    - name: Display success message
      debug:
        msg: "VyOS image builder test completed successfully! ISO created at /tmp/vyos-images/vyos-current.iso"
