---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yaml

driver:
  name: docker

platforms:
  - name: vyos-vlans-test
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    pre_build_image: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - "${VYOS_IMAGE_PATH:-../../../../../../images/vyos}:/images/vyos:ro"
    cgroupns_mode: host
    privileged: true
    capabilities:
      - SYS_ADMIN
      - NET_ADMIN
    groups:
      - nexus

provisioner:
  name: ansible
  inventory:
    host_vars:
      vyos-vlans-test:
        vyos_network_mode: bridge
        vyos_enable_vlans: true
        vyos_configure_host_vlans: true
        vyos_use_ovs: false  # Disable OVS in container
        vyos_test_mode: true
        vyos_iso_path: "/images/vyos/vyos-current.iso"

verifier:
  name: ansible
