---
- name: Wait for VyOS to be accessible
  ansible.builtin.wait_for:
    port: "{{ vyos_ssh_port | default(2222) }}"
    host: "{{ vyos_vm_ip | default('192.168.122.50') }}"
    delay: 60
    timeout: 300
  when: vyos_vm_ip is defined

# Configure physical interfaces
- name: Configure WAN interface base settings
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 description "WAN Interface"
      - set interfaces ethernet eth0 hw-id auto
  when: vyos_vm_ip is defined

- name: Configure WAN interface DHCP
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth0 address dhcp
  when: 
    - vyos_vm_ip is defined
    - vyos_wan_dhcp | default(true)

- name: Configure LAN trunk interface
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth1 description "LAN Trunk Interface"
      - set interfaces ethernet eth1 hw-id auto
  when: vyos_vm_ip is defined

# Configure VLANs and DHCP
- name: Configure VLAN interfaces
  vyos.vyos.vyos_config:
    lines:
      - "set interfaces ethernet eth1 vif {{ item.vlan_id }} description '{{ item.description }}'"
      - "set interfaces ethernet eth1 vif {{ item.vlan_id }} address {{ item.gateway }}/{{ item.subnet.split('/')[1] }}"
  loop: "{{ vyos_vlan_networks }}"
  when: vyos_vm_ip is defined

- name: Configure DHCP server for VLANs
  vyos.vyos.vyos_config:
    lines:
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} default-router {{ item.gateway }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} name-server {{ vyos_dns_servers | join(' ') }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} domain-name {{ item.name }}.homelab.local"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} range vlan{{ item.vlan_id }} start {{ item.dhcp_range.split('-')[0] }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} range vlan{{ item.vlan_id }} stop {{ item.dhcp_range.split('-')[1] }}"
      - "set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.subnet }} lease 86400"
  loop: "{{ vyos_vlan_networks }}"
  when: 
    - vyos_vm_ip is defined
    - item.dhcp_enabled

# Configure NAT
- name: Configure NAT masquerading
  vyos.vyos.vyos_config:
    lines:
      - set nat source rule 100 outbound-interface eth0
      - set nat source rule 100 source address 10.0.0.0/8
      - set nat source rule 100 translation address masquerade
  when: vyos_vm_ip is defined

# Configure DNS forwarding
- name: Configure DNS forwarding base settings
  vyos.vyos.vyos_config:
    lines:
      - set service dns forwarding listen-address 127.0.0.1
      - set service dns forwarding cache-size 1000
  when: vyos_vm_ip is defined

- name: Configure DNS forwarding listeners for VLANs
  vyos.vyos.vyos_config:
    lines:
      - "set service dns forwarding listen-address {{ item.gateway }}"
  loop: "{{ vyos_vlan_networks }}"
  when: vyos_vm_ip is defined

- name: Configure DNS forwarding name servers
  vyos.vyos.vyos_config:
    lines:
      - "set service dns forwarding name-server {{ item }}"
  loop: "{{ vyos_dns_servers }}"
  when: vyos_vm_ip is defined

# Configure NTP
- name: Configure NTP servers
  vyos.vyos.vyos_config:
    lines:
      - "set system ntp server {{ item }}"
  loop: "{{ vyos_ntp_servers }}"
  when: vyos_vm_ip is defined

# Configure SSH
- name: Configure SSH service
  vyos.vyos.vyos_config:
    lines:
      - "set service ssh port {{ vyos_ssh_port }}"
      - set service ssh listen-address 0.0.0.0
  when: vyos_vm_ip is defined

# Configure HTTPS web interface
- name: Configure HTTPS web interface
  vyos.vyos.vyos_config:
    lines:
      - set service https listen-address 0.0.0.0
      - "set service https port {{ vyos_web_port }}"
  when: vyos_vm_ip is defined

# Apply firewall configuration
- name: Configure firewall default policies
  vyos.vyos.vyos_config:
    lines:
      - set firewall all-ping enable
      - set firewall broadcast-ping disable
      - set firewall config-trap disable
      - set firewall ipv6-receive-redirects disable
      - set firewall ipv6-src-route disable
      - set firewall ip-src-route disable
      - set firewall log-martians enable
      - set firewall receive-redirects disable
      - set firewall send-redirects enable
      - set firewall source-validation disable
      - set firewall syn-cookies enable
      - set firewall twa-hazards-protection disable
  when: vyos_vm_ip is defined

# Configure VLAN firewall rules
- name: Configure firewall rules for VLANs
  include_tasks: configure_vlan_firewall.yaml
  loop: "{{ vyos_vlan_networks }}"
  loop_control:
    loop_var: vlan
  when: vyos_vm_ip is defined

# Configure WAN firewall
- name: Configure WAN firewall rules
  vyos.vyos.vyos_config:
    lines:
      - set firewall name WAN_IN default-action drop
      - set firewall name WAN_IN description "WAN inbound traffic"
      - set firewall name WAN_IN rule 10 action accept
      - set firewall name WAN_IN rule 10 state established enable
      - set firewall name WAN_IN rule 10 state related enable
      - set firewall name WAN_IN rule 20 action drop
      - set firewall name WAN_IN rule 20 state invalid enable
      - set interfaces ethernet eth0 firewall in name WAN_IN
  when: vyos_vm_ip is defined

# Save configuration
- name: Save VyOS configuration
  vyos.vyos.vyos_config:
    save: yes
  when: vyos_vm_ip is defined

- name: Configuration applied successfully
  ansible.builtin.debug:
    msg: "VyOS configuration has been applied and saved successfully!"
  when: vyos_vm_ip is defined
