- name: build vyos image
  hosts: fast-host
  gather_facts: no
  vars:
  vars:
    infisicalClientSecret: "{{ lookup('ansible.builtin.env', 'INFISICAL_CLIENT_SECRET', default=undef()) }}"
    systemSudoPassword: "{{ lookup(
      'infisical.vault.read_secrets',
      universal_auth_client_id='72fdfa59-56b2-4d2e-9dde-cd5a4d5ef3ea',
      universal_auth_client_secret=infisicalClientSecret,
      project_id='e0ff40f2-e63c-4ffc-9233-a66c46a47b2e',
      path='/',
      env_slug='prod',
      url='https://app.infisical.com',
      secret_name='systemSudoPassword',
      )
    }}"
    ansible_become_password: "{{ systemSudoPassword.value }}"
  tasks:
    - name: get versions
      ansible.builtin.include_vars:
        file: ../versions/build-vyos.json
        name: versions
    - name: install deps with specific versions
      become: true
      become_user: root
      ansible.builtin.apt:
        pkg:
          - "libvirt-daemon-system-systemd={{ versions.libvirtDaemonSystemSystemD }}"
        update_cache: yes
        state: present
    - name: install latest deps
      become: true
      become_user: root
      ansible.builtin.apt:
        pkg:
          - "qemu-kvm"
          - "libvirt-clients"
          - "bridge-utils"
        update_cache:
        state: present



