---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python3-docker
      ansible.builtin.apt:
        name:
          - python3-docker
        state: present
        update_cache: yes
      become: yes