---
- name: restart sshd
  systemd:
    name: sshd
    state: restarted

- name: restart auditd
  systemd:
    name: auditd
    state: restarted

- name: restart ufw
  systemd:
    name: ufw
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted 