---
# Ubuntu version: Edit ../.env.yml to change UBUNTU_VERSION and MOLECULE_DOCKER_IMAGE
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    pre_build_image: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    volumes:
      - "${MOLECULE_VOLUME_CGROUP:-/sys/fs/cgroup:/sys/fs/cgroup:rw}"
      - "${MOLECULE_VOLUME_KVM:-/dev/kvm:/dev/kvm}"
    cgroupns_mode: "${MOLECULE_CGROUPNS_MODE:-host}"
    privileged: ${MOLECULE_PRIVILEGED:-true}
    capabilities:
      - "${MOLECULE_CAPABILITY_SYS_ADMIN:-SYS_ADMIN}"
    groups:
      - "${MOLECULE_GROUP:-nexus}"
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      retry_files_enabled: false
      host_key_checking: false
      remote_tmp: /tmp/ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker
verifier:
  name: ansible
