---
- name: Verify
  hosts: all
  tasks:
    - name: Check if mock ISO exists
      stat:
        path: "/tmp/vyos-images/vyos-current.iso"
      register: iso_file

    - name: Verify mock ISO is created
      assert:
        that:
          - iso_file.stat.exists
        fail_msg: "Mock VyOS ISO not created at expected location"

    - name: Verify mock ISO size
      assert:
        that:
          - iso_file.stat.size > 450000000  # ~450MB for mock
          - iso_file.stat.size < 500000000  # Should be exactly 450MB
        fail_msg: "Mock ISO size incorrect ({{ iso_file.stat.size }} bytes)"

    - name: Check symlink to latest ISO
      stat:
        path: "/tmp/vyos-images/vyos-latest.iso"
      register: latest_link

    - name: Verify latest symlink exists
      assert:
        that:
          - latest_link.stat.exists
          - latest_link.stat.islnk
        fail_msg: "Latest ISO symlink not created"

    - name: Test idempotency - run role again
      include_role:
        name: ../../../roles/vyos_image_builder
      vars:
        vyos_test_mode: true

    - name: Find all ISO files after second run
      find:
        paths: /tmp/vyos-images
        patterns: "vyos-*.iso"
        file_type: file
      register: iso_count

    - name: Verify no duplicate build (idempotency)
      assert:
        that:
          - iso_count.files | length == 1
        fail_msg: "Multiple ISOs found, idempotency check failed"

    - name: Display success message
      debug:
        msg: "VyOS mock image builder test completed successfully!"
