---
- name: Converge
  hosts: all
  tasks:
    - name: Install required packages for testing
      apt:
        name:
          - cloud-image-utils
          - python3-lxml
          - python3-libvirt
          - qemu-utils
          - file
          - python3-passlib
        state: present
        update_cache: true

    - name: Check if real VyOS ISO exists
      stat:
        path: "{{ vyos_iso_path | default('/images/vyos/vyos-current.iso') }}"
      register: vyos_iso_check
      failed_when: not vyos_iso_check.stat.exists

    - name: Verify VyOS ISO is valid
      command: "file {{ vyos_iso_path | default('/images/vyos/vyos-current.iso') }}"
      register: iso_type
      changed_when: false
      failed_when: "'ISO 9660' not in iso_type.stdout"

    - name: Include vyos_setup role
      include_role:
        name: ../../../roles/vyos_setup
