---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: vyos-setup-test
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    pre_build_image: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /dev/kvm:/dev/kvm
    cgroupns_mode: host
    privileged: true
    capabilities:
      - SYS_ADMIN
    groups:
      - nexus

provisioner:
  name: ansible
  inventory:
    host_vars:
      vyos-setup-test:
        vyos_network_mode: nat
        vyos_build_image: false
        vyos_iso_path: /tmp/test-vyos.iso
        vyos_configure_router: true
        vyos_enable_vlans: false
        vyos_security_hardening: false
        vyos_cloud_init_enabled: true
        vyos_admin_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtest test@homelab"

verifier:
  name: ansible