---
- name: Prepare
  hosts: all
  tasks:
    - name: Install openssh-client for ssh-keygen
      apt:
        name: openssh-client
        state: present
        update_cache: true

    - name: Set test mode fact
      set_fact:
        vyos_test_mode: true

    - name: Create test SSH key pair
      command: ssh-keygen -t rsa -b 2048 -f /tmp/test_ssh_key -N ""
      args:
        creates: /tmp/test_ssh_key

    - name: Read test SSH public key
      slurp:
        src: /tmp/test_ssh_key.pub
      register: test_ssh_pub_key

    - name: Read test SSH private key
      slurp:
        src: /tmp/test_ssh_key
      register: test_ssh_priv_key

    - name: Set test values for VyOS
      set_fact:
        # Plain text password for testing
        vyos_admin_password: "TestPassword123!"
        vyos_ansible_ssh_key: "{{ test_ssh_pub_key.content | b64decode | trim }}"
        vyos_ansible_ssh_private_key: "{{ test_ssh_priv_key.content | b64decode }}"
      when: vyos_test_mode | default(false)