---
- name: Verify
  hosts: all
  tasks:
    - name: Check if VM is defined
      command: virsh list --all
      register: vm_list
      changed_when: false

    - name: Verify VyOS VM exists
      assert:
        that:
          - "'vyos-router' in vm_list.stdout"
        fail_msg: "VyOS VM not found in libvirt"

    - name: Check if VM is running
      command: virsh domstate vyos-router
      register: vm_state
      changed_when: false

    - name: Verify VM is running
      assert:
        that:
          - vm_state.stdout == "running"
        fail_msg: "VyOS VM is not running"

    - name: Check cloud-init ISO exists
      stat:
        path: /var/lib/libvirt/images/vyos-cloud-init.iso
      register: cloud_init_iso

    - name: Verify cloud-init ISO was created
      assert:
        that:
          - cloud_init_iso.stat.exists
        fail_msg: "Cloud-init ISO not found"

    - name: Check libvirt networks
      command: virsh net-list
      register: net_list
      changed_when: false

    - name: Verify networks are active
      assert:
        that:
          - "'wan' in net_list.stdout"
          - "'lan' in net_list.stdout"
        fail_msg: "Required networks not active"
