---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: restart ufw
  service:
    name: ufw
    state: restarted 