---
- name: Setup Nexus Node
  hosts: nexus
  become: true
  gather_facts: true
  
  vars:
    infisicalClientSecret: "{{ lookup('ansible.builtin.env', 'INFISICAL_CLIENT_SECRET', default=undef()) }}"
    systemSudoPassword: "{{ lookup(
      'infisical.vault.read_secrets',
      universal_auth_client_id='72fdfa59-56b2-4d2e-9dde-cd5a4d5ef3ea',
      universal_auth_client_secret=infisicalClientSecret,
      project_id='e0ff40f2-e63c-4ffc-9233-a66c46a47b2e',
      path='/',
      env_slug='prod',
      url='https://app.infisical.com',
      secret_name='systemSudoPassword',
      )
    }}"
    ansible_become_password: "{{ systemSudoPassword.value }}"
    
    # Network configuration
    wan_interface: enp1s0f0
    lan_interface: enp1s0f1
    
    # VyOS VM configuration
    vyos_vm:
      name: vyos-1.5
      memory: 4096  # 4GB RAM
      vcpus: 2
      disk_size: 20G
      iso_path: /var/lib/libvirt/images/vyos-1.5-rolling-202504270204-generic-amd64.iso
      disk_path: /var/lib/libvirt/images/vyos-1.5.qcow2

    # Services VM configuration
    services_vm:
      name: nexus-services
      memory: 4096  # 4GB RAM
      vcpus: 2
      disk_size: 40G
      iso_path: /var/lib/libvirt/images/ubuntu-22.04-server-amd64.iso
      disk_path: /var/lib/libvirt/images/nexus-services.qcow2

  roles:
    - role: homelab.nexus.security.hardening
    - role: homelab.nexus.vyos.setup
    - role: homelab.nexus.services.vm.setup
    - role: homelab.nexus.system.setup

  tasks:
    - name: Include version information
      ansible.builtin.include_vars:
        file: ../versions/nexus.json
        name: versions 