---
# Site-wide playbook that deploys all infrastructure

- name: Configure Nexus Node
  import_playbook: setup-nexus.yaml
  tags: [nexus]

- name: Configure EPYC Harvester Cluster
  import_playbook: setup-epyc.yaml
  tags: [epyc, harvester] 