---
- name: Converge
  hosts: all
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - libvirt-daemon-system
          - qemu-kvm
          - libvirt-clients
          - bridge-utils
          - virtinst
          - systemd
        state: present

    - name: Start and enable libvirt
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: true

    - name: Include services VM setup role
      ansible.builtin.include_role:
        name: homelab.nexus.services_vm_setup 