---
- name: Check if VyOS image already exists
  stat:
    path: "{{ vyos_images_dir }}/vyos-{{ vyos_version }}.iso"
  register: vyos_image

- name: Build VyOS image
  when: not vyos_image.stat.exists
  block:
    - name: Create mock ISO for testing
      when: vyos_test_mode | default(false)
      block:
        # Note: Test mode creates images in a different directory (e.g., /tmp/vyos-images)
        # Production uses ../images/vyos relative to playbook_dir
        - name: Ensure images directory exists
          file:
            path: "{{ vyos_images_dir }}"
            state: directory
            mode: '0755'

        - name: Create mock VyOS ISO
          command: dd if=/dev/zero of="{{ vyos_images_dir }}/vyos-{{ vyos_version }}.iso" bs=1M count=450
          args:
            creates: "{{ vyos_images_dir }}/vyos-{{ vyos_version }}.iso"

        - name: Create symlink to latest ISO
          file:
            src: "vyos-{{ vyos_version }}.iso"
            dest: "{{ vyos_images_dir }}/vyos-latest.iso"
            state: link

- name: Build real VyOS image
  when: 
    - not vyos_image.stat.exists
    - not (vyos_test_mode | default(false))
  block:
    - name: Check if Docker is already available
      command: docker version
      register: docker_check
      ignore_errors: yes
      changed_when: false

    - name: Install Docker and dependencies
      apt:
        name:
          - docker.io
          - git
          - curl
        state: present
        update_cache: yes
      when: docker_check.rc != 0

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
      when: docker_check.rc != 0

    - name: Install Docker client for Docker-in-Docker
      apt:
        name:
          - docker.io
          - git
          - curl
        state: present
        update_cache: yes
      when: docker_check.rc == 0

    - name: Add ansible user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      notify: cleanup build directory
      when: docker_check.rc != 0

    - name: Reset connection to apply group changes
      meta: reset_connection
      when: docker_check.rc != 0

    - name: Create build directory
      file:
        path: "{{ vyos_build_dir }}"
        state: directory
        mode: '0755'

    - name: Clone VyOS build repository
      git:
        repo: https://github.com/vyos/vyos-build.git
        dest: "{{ vyos_build_dir }}/vyos-build"
        version: "{{ vyos_version }}"
        force: yes
      ignore_errors: yes

    - name: Check git clone result
      stat:
        path: "{{ vyos_build_dir }}/vyos-build/.git"
      register: git_clone_check

    - name: Clone with correct branch if first attempt failed
      git:
        repo: https://github.com/vyos/vyos-build.git
        dest: "{{ vyos_build_dir }}/vyos-build"
        version: current
        force: yes
      when: not git_clone_check.stat.exists

    - name: Pull VyOS build Docker image
      docker_image:
        name: "{{ vyos_docker_image }}"
        source: pull
        state: present

    - name: Build VyOS ISO using Docker
      docker_container:
        name: vyos-builder
        image: "{{ vyos_docker_image }}"
        command: /bin/bash -c "cd /vyos && ./configure && make iso"
        volumes:
          - "{{ vyos_build_dir }}/vyos-build:/vyos"
        working_dir: /vyos
        detach: no
        cleanup: yes
        auto_remove: no
        env:
          BUILD_BY: "{{ vyos_build_by }}"
          BUILD_TYPE: "{{ vyos_build_type }}"
          BUILD_ARCH: "{{ vyos_architecture }}"
      register: build_result
      ignore_errors: yes

    - name: Get container logs on failure
      command: docker logs vyos-builder
      when: build_result is failed
      register: build_logs
      ignore_errors: yes

    - name: Display build logs on failure
      debug:
        var: build_logs.stdout_lines
      when: build_result is failed and build_logs is defined

    - name: Remove builder container
      docker_container:
        name: vyos-builder
        state: absent
      when: build_result is defined

    - name: Fail if build failed
      fail:
        msg: "VyOS build failed. Check logs above for details."
      when: build_result is failed

    - name: Ensure images directory exists
      file:
        path: "{{ vyos_images_dir }}"
        state: directory
        mode: '0755'

    - name: Find built ISO
      find:
        paths: "{{ vyos_build_dir }}/vyos-build/build"
        patterns: "vyos-*.iso"
      register: built_iso

    - name: Verify ISO was built
      fail:
        msg: "VyOS ISO build failed - no ISO found in build directory"
      when: built_iso.files | length == 0

    - name: Copy ISO to images directory
      copy:
        src: "{{ built_iso.files[0].path }}"
        dest: "{{ vyos_images_dir }}/vyos-{{ vyos_version }}.iso"
        remote_src: yes
        mode: '0644'

    - name: Create symlink to latest ISO
      file:
        src: "vyos-{{ vyos_version }}.iso"
        dest: "{{ vyos_images_dir }}/vyos-latest.iso"
        state: link

  always:
    - name: Cleanup build directory
      file:
        path: "{{ vyos_build_dir }}"
        state: absent
      when: vyos_build_cleanup | default(true)
      tags: [cleanup]

- name: Display image location
  debug:
    msg: "VyOS image available at: {{ vyos_images_dir }}/vyos-{{ vyos_version }}.iso"