---
# Shared molecule configuration for homelab.nexus collection
# This file defines common settings across all molecule scenarios
# Individual scenarios can override these settings as needed

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      retry_files_enabled: false
      host_key_checking: false
      remote_tmp: /tmp/ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint