---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - git
      - curl
      - wget
      - vim
      - htop
      - net-tools
      - bridge-utils
      - openvswitch-switch
      - python3-pip
      - python3-venv
    state: present

- name: Create system directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /var/lib/libvirt/images
    - /opt/nexus
    - /opt/nexus/config
    - /opt/nexus/scripts

- name: Set up network bridges
  template:
    src: netplan.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    mode: '0644'
  notify: apply netplan

- name: Configure system limits
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    mode: '0644'

- name: Configure sysctl parameters
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: '0644'
  notify: apply sysctl

- name: Set up Python virtual environment
  command:
    cmd: python3 -m venv /opt/nexus/venv
    creates: /opt/nexus/venv

- name: Install Python packages
  pip:
    name:
      - ansible
      - kubernetes
      - openshift
    virtualenv: /opt/nexus/venv
    state: present

- name: Create systemd service directory
  file:
    path: /etc/systemd/system
    state: directory
    mode: '0755'

- name: Set up systemd services
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - { src: 'libvirtd.service.j2', dest: '/etc/systemd/system/libvirtd.service' }
  notify: reload systemd 