---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: harvester-setup
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    pre_build_image: true
    command: "${MOLECULE_COMMAND:-/lib/systemd/systemd}"
    volumes:
      - "${MOLECULE_VOLUME_CGROUP:-/sys/fs/cgroup:/sys/fs/cgroup:rw}"
    cgroupns_mode: "${MOLECULE_CGROUPNS_MODE:-host}"
    privileged: ${MOLECULE_PRIVILEGED:-true}
    capabilities:
      - "${MOLECULE_CAPABILITY_SYS_ADMIN:-SYS_ADMIN}"
    groups:
      - "${MOLECULE_GROUP:-epyc}"
provisioner:
  name: ansible
  config_options:
    defaults:
      collections_paths: /home/user/IdeaProjects/homelab-ansible/collections
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible