---
- name: restart services
  community.docker.docker_compose:
    project_src: /opt/services
    state: present
    pull: true
    force_restart: true

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
