---
- name: Converge
  hosts: all
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - systemd
        state: present

    - name: Test basic system functionality
      ansible.builtin.debug:
        msg: "Default scenario - basic system test completed" 